Generate ssdk error tests
awslabs/smithy-typescript pull request #293
Opened 2021-03-23 18:08 UTC by JordonPhillips

This updates the http protocol test generator to include error tests. A generated test looks like:

```typescript
it("RestJsonInvalidGreetingError:ServerErrorResponse", async () => {
  class TestService implements Partial<RestJsonService> {
    GreetingWithErrors(input: any, request: HttpRequest): GreetingWithErrorsServerOutput {
      const response = {
        Message: "Hi",
      } as any;
      const error: InvalidGreeting = {
        ...response,
        name: "InvalidGreeting",
        $fault: "client",
        $metadata: {},
      };
      throw error;
    }
  }
  const service: any = new TestService();
  const testMux = new httpbinding.HttpBindingMux<"RestJson", keyof RestJsonService>([
    new httpbinding.UriSpec<"RestJson", "GreetingWithErrors">("POST", [], [], {
      service: "RestJson",
      operation: "GreetingWithErrors",
    }),
  ]);
  const request = new HttpRequest({ method: "POST", hostname: "example.com" });
  class TestSerializer extends GreetingWithErrorsSerializer {
    deserialize = (output: any, context: any): Promise<any> => {
      return Promise.resolve({});
    };
  }
  const serFn: (
    op: RestJsonServiceOperations
  ) => __OperationSerializer<RestJsonService, RestJsonServiceOperations, __SmithyException> = (op) => {
    return new TestSerializer();
  };
  const handler = new RestJsonServiceHandler(service, testMux, serFn);
  let r = await handler.handle(request);

  expect(r.statusCode).toBe(400);

  expect(r.headers["content-type"]).toBeDefined();
  expect(r.headers["content-type"]).toBe("application/json");
  expect(r.headers["x-amzn-errortype"]).toBeDefined();
  expect(r.headers["x-amzn-errortype"]).toBe("InvalidGreeting");

  expect(r.body).toBeDefined();
  const utf8Encoder = __utf8Encoder;
  const bodyString = `{
                \"Message\": \"Hi\"
            }`;
  const unequalParts: any = compareEquivalentJsonBodies(bodyString, r.body.toString());
  expect(unequalParts).toBeUndefined();
});
```

Additionally, I tweaked the `serializeError` for operations with no modeled errors to immediately throw. Before it was creating an empty switch statement which would cause TypeScript to fail to compile since the errors union is `never`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-23 18:11 UTC, adamthom-amzn approved these changes

2021-03-23 18:11 UTC, adamthom-amzn commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
> +                if (!error.hasTag("server-only")) {
what does this tag mean?

2021-03-24 16:43 UTC, kstich requested changes

2021-03-24 16:43 UTC, kstich commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
> +        Symbol serviceSymbol = serverSymbolProvider.toSymbol(service);
minor: would be nice to have some more spacing and comments in here describing what's being done.

2021-03-24 18:35 UTC, kstich approved these changes

2021-03-25 11:25 UTC, merged