Update serde interfaces to differentiate in/out
awslabs/smithy-typescript pull request #305
Opened 2021-04-07 13:54 UTC by JordonPhillips

This updates the interfaces for rest services to differentiate when an operation's input vs output vs error is being serialized / deserialized. This is necessary because there can be subtly different rules in each case.

Right now this is pretty ugly so I put it up as a draft. The major alternative I am considering is to instead have explicit methods for each case, e.g:

```java
protected abstract void serializeInputDocumentBody(
    GenerationContext context,
    OperationShape operation,
    List<HttpBinding> documentBindings
);

protected abstract void serializeOutputDocumentBody(
    GenerationContext context,
    OperationShape operation,
    List<HttpBinding> documentBindings
);

protected abstract void serializeErrorDocumentBody(
    GenerationContext context,
    OperationShape operation,
    StructureShape error,
    List<HttpBinding> documentBindings
);
```

Implementers could then make it generic on their end if necessary as apposed to having to split things up like is the case now.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-19 21:02 UTC, adamthom-amzn approved these changes
I don't like adding a boolean flag to methods in general, but looking at the structure of methods like `writeContentTypeHeader` I think you may end up having a private method with the flag added anyway.

2021-04-29 19:37 UTC, kstich requested changes

2021-04-29 19:37 UTC, kstich commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
> +     * Writes the code needed to serialize the output payload of a request.
s/request/response

2021-04-29 19:37 UTC, kstich commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
> +     * {@code body} variable that will be serialized as the request body.
s/request/response

2021-04-29 19:37 UTC, kstich commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
> +     * Writes the code needed to serialize the error payload of a request.
s/request/response

2021-04-29 19:37 UTC, kstich commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
> +     * {@code body} variable that will be serialized as the request body.
s/request/response

2021-04-29 19:37 UTC, kstich commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
> +     * Writes the code needed to deserialize the output payload of a request.
s/request/response

2021-04-29 19:37 UTC, kstich commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
> +     * Writes the code needed to deserialize the input payload of a request.
s/request/response

2021-05-06 16:08 UTC, adamthom-amzn approved these changes

2021-05-11 17:30 UTC, kstich approved these changes

2021-05-12 11:11 UTC, JordonPhillips commented
rebased so tests can be run one more time

2021-05-12 12:40 UTC, merged