feat(codegen): pass settings to get clients plugins
awslabs/smithy-typescript pull request #609
Opened 2022-10-05 13:29 UTC by eduardomourar

*Issue #, if available:* N/A

*Description of changes:*

In order to allow customization of plugins during initialization (e.g. checking if client or server SDK is being generated), we need to pass the Smithy build settings.

BREAKING CHANGE: Codegen users must migrate from `TypeScriptIntegration.getClientPlugins()` to `getClientPlugins(TypeScriptSettings settings)`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-12 21:37 UTC, srchase requested changes
Is this still needed? If so, can it get rebased so it can be merged?

2022-12-13 14:40 UTC, eduardomourar commented
> Is this still needed? If so, can it get rebased so it can be merged?

Yes, it is still needed. I have rebased.

2022-12-13 21:43 UTC, srchase commented
> > Is this still needed? If so, can it get rebased so it can be merged?
> 
> Yes, it is still needed. I have rebased.

It looks like this is still quite a ways behind main (~30 commits). Could you rebase to the latest on main so that this can be tested with aws-sdk-js-v3?

2023-01-20 19:55 UTC, eduardomourar commented
@srchase , could this be approved and merged, please?

2023-01-30 23:03 UTC, srchase commented
Sorry for the delay. Took another look at this. Can you help me understand your use case a bit more? Originally, this only gathered client runtime plugins, and that was kind of built into the name,`getClientPlugins()`. If this needs to be repurposed for returning non-client specific runtime plugins, maybe that should get updated too since this will be breaking anyways.

If you can share, what kind of server runtime plugin are you looking to differentiate with the settings?

2023-01-31 01:44 UTC, eduardomourar commented
> Sorry for the delay. Took another look at this. Can you help me understand your use case a bit more? Originally, this only gathered client runtime plugins, and that was kind of built into the name,`getClientPlugins()`. If this needs to be repurposed for returning non-client specific runtime plugins, maybe that should get updated too since this will be breaking anyways.
> 
> If you can share, what kind of server runtime plugin are you looking to differentiate with the settings?

I don't know why I mentioned server on this PR because I need this change for the client.

My use case is actually to create a unified auth mechanism that will take into account any method (for now only API Key and Bearer Token) added to through the Smith @auth trait. In order for this to work, we need to make certain choices [here](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java#L83-L100) either based on the model or coming from the Smithy build settings.

I would imagine this change is relevant to other situations where you need to conditionally add or remove based on the Smithy build settings provided.

2023-01-31 20:02 UTC, srchase commented
> > Sorry for the delay. Took another look at this. Can you help me understand your use case a bit more? Originally, this only gathered client runtime plugins, and that was kind of built into the name,`getClientPlugins()`. If this needs to be repurposed for returning non-client specific runtime plugins, maybe that should get updated too since this will be breaking anyways.
> > If you can share, what kind of server runtime plugin are you looking to differentiate with the settings?
> 
> I don't know why I mentioned server on this PR because I need this change for the client.
> 
> My use case is actually to create a unified auth mechanism that will take into account any method (for now only API Key and Bearer Token) added to through the Smith @auth trait. In order for this to work, we need to make certain choices [here](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java#L83-L100) either based on the model or coming from the Smithy build settings.
> 
> I would imagine this change is relevant to other situations where you need to conditionally add or remove based on the Smithy build settings provided.

As an alternative, would a `matchesSetting` method on [RuntimeClientPlugin](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java) work for your use case? That would work like the existing [matchesService](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java#L269-L286) and [matchesOperation](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java#L288-L299) methods than can be used to filter plugins already. For example, CommandGenerator filters its runtime plugins based on the operation [here](https://github.com/awslabs/smithy-typescript/blob/main/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java#L91).

2023-01-31 21:11 UTC, eduardomourar commented
> As an alternative, would a `matchesSetting` method on [RuntimeClientPlugin](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java) work for your use case? That would work like the existing [matchesService](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java#L269-L286) and [matchesOperation](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java#L288-L299) methods than can be used to filter plugins already. For example, CommandGenerator filters its runtime plugins based on the operation [here](https://github.com/awslabs/smithy-typescript/blob/main/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java#L91).

That would work for me, yes.

2023-02-02 19:59 UTC, gosar commented
It is still unclear whether this PR or the other [PR](https://github.com/awslabs/smithy-typescript/pull/684) or another different solution is better suited to solve your use case.

> My use case is actually to create a unified auth mechanism that will take into account any method (for now only API Key and Bearer Token) added to through the Smith @auth trait. In order for this to work, we need to make certain choices [here](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java#L83-L100) either based on the model or coming from the Smithy build settings.

I could see making choices based on model but can you explain the case based on build settings? The names of these settings will also help understand this solution.

> > As an alternative, would a `matchesSetting` method on [RuntimeClientPlugin](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java) work for your use case? That would work like the existing [matchesService](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java#L269-L286) and [matchesOperation](https://github.com/awslabs/smithy-typescript/blob/f29d213f17bf46be5fb718cbd8cb03e184ed2e0e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java#L288-L299) methods than can be used to filter plugins already. For example, CommandGenerator filters its runtime plugins based on the operation [here](https://github.com/awslabs/smithy-typescript/blob/main/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java#L91).
> 
> That would work for me, yes.

Can you explain where you would call this potential `matchesSettings` from?

2023-08-24 05:55 UTC, syall commented
Since https://github.com/awslabs/smithy-typescript/pull/856, this PR is a duplicate.

2023-08-24 05:55 UTC, closed without merging