shorten internal serde fn names
awslabs/smithy-typescript pull request #730
Opened 2023-04-03 20:16 UTC by kuhe

Shorten generated serde function names. Source code contains a comment with the original long name, distribution uses short names.

- [ ] do not merge, needs JSv3 codegen changes PR (TBD)

2023-04-04 20:46 UTC, kuhe commented
Update: no longer shortening the symbol/shape name to prevent thrashing on the function names. Many names

2023-04-05 15:04 UTC, pose requested changes
Why is this required and cannot be achieved by properly configuring bundling and minifying with esbuild/webpack?

2023-04-05 15:50 UTC, kuhe commented
This is not required, but it benefits users who use the generated clients as they are without minifying. One example is the AWS Lambda provided AWS SDK for JavaScript v3 that users do not bundle into their AWS Lambda applications.

2023-04-05 16:07 UTC, mtdowling commented
Can you update the description to show the current state of what this generates? I'd like these names to be stable cross model updates too, which I think you already added. Is it now `[se|de]_ShapeName`?

2023-04-05 16:22 UTC, pose commented
Why does the AWS Lambda provided AWS SDK for JavaScript v3 cannot be minified?

2023-04-05 17:23 UTC, kuhe commented
Yes, the PR currently is only a change to `[se|de]_ShapeName` which is stable over model changes. I've updated the original description.

> Why does the AWS Lambda provided AWS SDK for JavaScript v3 cannot be minified?

The AWS Lambda provided AWS SDKs are supposedly for development/testing/convenience purposes, [link](https://docs.aws.amazon.com/lambda/latest/operatorguide/sdks-functions.html) and should retain readable stack traces without mangling and minification, but customers often prefer to continue to use them for production workloads. 

We can provide some benefit to those users without needing to change customer behavior. However, if you think the risk of this change is greater than the potential benefits, I'm fine with closing it.

2023-04-05 17:25 UTC, pose approved these changes

2023-04-05 22:22 UTC, trivikr approved these changes

2023-04-05 22:42 UTC, mtdowling commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
> +    default Map<String, ShapeId> getOperationErrors(GenerationContext context,
nit - we wrap at 120

2023-04-05 22:56 UTC, srchase commented
Can all the auto-formatting be undone on this? It's hard to read the actual changes and this will be an unnecessarily noisy commit.

2023-04-06 16:36 UTC, srchase approved these changes

2023-04-06 21:24 UTC, merged