add packageDocumentation and improve interface inheritance
awslabs/smithy-typescript pull request #770
Opened 2023-05-22 19:13 UTC by MYoung25

*Description of changes:*
1. Add packageDocumentation trait with service documentation
2. Export types used in inheritance chain to allow documentation to follow the entire chain
    1.  export imported types to allow them to be inherited
    2. export default types to allow them to be inherited

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-22 22:54 UTC, trivikr approved these changes

2023-05-22 23:04 UTC, syall approved these changes

2023-05-22 23:10 UTC, syall requested changes
Would it be possible to put examples of the generated diffs in the PR description, and see if the output TypeScript compiles with the additional export statements and formatting?

2023-05-22 23:10 UTC, syall commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
> +        writer.write("export { __Client }\n");
Was wondering if this should be the following?

```suggestion
        writer.write("export { __Client };");
```

2023-05-22 23:10 UTC, syall commented on smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddBaseServiceExceptionClass.java
> +                            writer.write("export { __ServiceException, __ServiceExceptionOptions }\n");
Was wondering if this should be the following?

```suggestion
                            // Export ServiceException information to allow
                            //      documentation inheritance to consume their types
                            writer.write("export { __ServiceException, __ServiceExceptionOptions }?");
```

2023-05-23 14:45 UTC, syall approved these changes

2023-05-23 14:47 UTC, merged